feat(build-package): Forbid building accelerated packages that are still initializing (#172)
- Forbid building an instance of a package unless it's completed its
initial sync

## Test plan

On an accelerated version in state "Error syncing initial":
```
% cargo run -- build-package -p automatically-fast@0.1.6 nodejs
    Finished dev [unoptimized + debuginfo] target(s) in 5.90s
     Running `target/debug/dpm build-package -p 'automatically-fast@0.1.6' nodejs`
package build failed: The package you requested to build failed to complete its initial acceleration.

Error: An unknown error occurred

Because it would be potentially confusing for an instance of an "accelerated" package
version to execute its queries without acceleration, the build will abort now.
Resolve the error above, then try building again.
```

On an accelerated version in state "Syncing":
```
% cargo run -- build-package -p automatically-fast@0.1.9 nodejs
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/dpm build-package -p 'automatically-fast@0.1.9' nodejs`
Going to generate a data-package in NodeJs { scope: None }
Data package already exists at "dist/nodejs/automatically-fast@0.1.9-0.2.2", overwrite? yes
Overwriting
...
```