feat: Update `describe` and `update` for named sources (#109)
- Update dpm-agent protos
- Update `describe` and `update` to work with named sources

This removes the awareness of the `SNOWSQL` env vars from the app.

Recommend reviewing commit by commit.

## Test plan

When the source was created with incorrect username/password:
```
% DPM_API_URL=https://dev.api.dpm.sh DPM_AGENT_URL=http://localhost:50051 cargo run describe -p somethin "source-1"
    Finished dev [unoptimized + debuginfo] target(s) in 0.22s
     Running `target/debug/dpm describe -p somethin source-1`
connected to http://localhost:50051/
introspecting ...
thread 'main' panicked at 'error during `ExecuteQuery`: Status { code: Unknown, message: "Failed to connect to Snowflake: 250001 (08001): None: Failed to connect to DB: YT23805-FH89891.snowflakecomputing.com:443. Incorrect username or password was specified.", source: None }', /Users/spencer/code/dpm/src/command/snowflake.rs:169:19
```

When I given a nameless source
```
% DPM_API_URL=https://dev.api.dpm.sh DPM_AGENT_URL=http://localhost:50051 cargo run describe -p somethin "does not exist"
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/dpm describe -p somethin 'does not exist'`
describe failed: Failed to get source: https://dev.api.dpm.sh/sources/does%20not%20exist => 404 Not Found, body: {"message":"Not found","description":"Not all those who wander are lost"}
```

Success, given ID:
```
% DPM_API_URL=https://dev.api.dpm.sh DPM_AGENT_URL=http://localhost:50051 cargo run -- describe -p somethin "c98449ff-fd96-467d-8360-c1a625f00fa9" snowflake --schema PUBLIC
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/dpm describe -p somethin c98449ff-fd96-467d-8360-c1a625f00fa9 snowflake --schema PUBLIC`
connected to http://localhost:50051/
introspecting ...
wrote descriptor: datapackage.json
```

Success, given name:
```
% DPM_API_URL=https://dev.api.dpm.sh DPM_AGENT_URL=http://localhost:50051 cargo run -- describe -p somethin "first-source" snowflake --schema PUBLIC
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/dpm describe -p somethin first-source snowflake --schema PUBLIC`
connected to http://localhost:50051/
introspecting ...
wrote descriptor: datapackage.json
```