fix: indexing on operands function rather than trait (#87)
Found during unit testing of python data packages. Was causing the
error: `TypeError: 'method' object is not subscriptable` when trying to
create a graphql field for an aggregate expression