fix(env): Update user_agent to support environments w/o git metadata (#119)
- Support `user_agent` in git-less builds

The build environment created by
https://github.com/patch-tech/rust-build.action does not have the `.git`
dir and so the git-based build metadata is unavailable in the resulting
binary, causing the `.unwrap` call here to panic.

I'm not sure what would be involved in making the .git dir available in
the build container, but this should suffice for now.

## Test plan

On `main`:
```
# Take away git metadata
mv .git .git2
rm -r target/
cargo test
...
---- test_nodejs stdout ----
thread 'test_nodejs' panicked at 'Command ("cargo" "run" "source" "create" "snowflake" "-n" "integration-test_1692299687689" "--organization" "YT23805" "--account" "FH89891" "--database" "DEMO_DB" "--user" "PATCH_STREAM_U
SER" "--password" "<redacted>" "--warehouse" "COMPUTE_WH") failed (exit status: 101)

=== stdout ===

<empty>

=== stderr ===

    Blocking waiting for file lock on package cache
    Finished dev [unoptimized + debuginfo] target(s) in 0.27s
     Running `target/debug/dpm source create snowflake -n integration-test_1692299687689 --organization YT23805 --account FH89891 --database DEMO_DB --user PATCH_STREAM_USER --password l3cDfd7f4BdX --warehouse COMPUTE_WH`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/env.rs:43:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

==============
```
In this branch:
```
# Take away git metadata
mv .git .git2
rm -r target/
cargo test
...
running 2 tests
test test_nodejs ... ok
test test_python ... ok
```